name: Docker Build Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker-build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        tags: wine-api:test
        cache-from: type=gha
        cache-to: type=gha,mode=max

       # TODO: this to be verified when we have a database around
#    - name: Test container startup
#      run: |
#        docker run --rm -d --name wine-api-test -p 3000:3000 wine-api:test
#        sleep 10
#        docker logs wine-api-test
#        docker stop wine-api-test
